# Consulta SPARQL
# Descripción: ¿Cómo ha evolucionado el número de turistas mes a mes por comunidad autónoma durante el año 2024?

PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX inelod: <https://stats.linkeddata.es/voc/cubes/vocabulary#> 
PREFIX sdmx-dim: <http://purl.org/linked-data/sdmx/2009/dimension#>

SELECT ?comunidad ?periodo (SUM(?numTuristas) AS ?total)
WHERE {
  ?obs a qb:Observation ;
       inelod:ccaa ?comunidad ;
       sdmx-dim:refPeriod ?periodo ;
       inelod:numberOfTouristsABSValue ?numTuristas .
  FILTER(STRSTARTS(STR(?periodo), "2024"))
}
GROUP BY ?comunidad ?periodo
ORDER BY ?comunidad ?periodo