# LN: ¿Cuál fue el número de inmigrantes por país de nacimiento en 2022?

PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX sdmx-dim:<http://purl.org/linked-data/sdmx/2009/dimension#>
PREFIX sdmx-measure: <http://purl.org/linked-data/sdmx/2009/measure#>
PREFIX inelod:       <https://stats.linkeddata.es/voc/cubes/vocabulary#>

SELECT ?paisNacimiento (SUM(?cantidad) AS ?total)
WHERE {
  ?obs a qb:Observation ;
       sdmx-dim:refPeriod "2022" ;
       inelod:countryOfBirth ?paisNacimiento ;
       sdmx-measure:obsValue ?cantidad .
}
GROUP BY ?paisNacimiento
ORDER BY DESC(?total)