#Lista de niveles de una clasifiación CLASI
#LN: ¿Cuáles son los niveles jerárquicos de la clasificación 'CLASI'?

PREFIX  xkos: <http://rdf-vocabulary.ddialliance.org/xkos#> 
PREFIX skos: <http://www.w3.org/2004/02/skos/core#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>  
SELECT DISTINCT ?x ?y ?z WHERE { 
    ?x ?y ?z.  ?x rdf:type xkos:ClassificationLevel. 
    ?x skos:inScheme <http://stats.linkeddata.es/voc/clasificaciones/{{CLASI}}>. 
    }