#Lista de relaciones jerárquicas entre conceptos
# LN: Muéstrame la estructura jerárquica de la clasificación 'X'.

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  xkos: <http://rdf-vocabulary.ddialliance.org/xkos#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
SELECT ?parentLabel ?childLabel
WHERE {
  ?parent skos:inScheme <http://stats.linkeddata.es/voc/clasificaciones//{CLASI}> ;
          skos:prefLabel ?parentLabel .
  ?child skos:broader ?parent ;
         skos:prefLabel ?childLabel .
}